{% set name = "gemmi" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/project-gemmi/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 651cc7d3077508b5d88de9650677c0ef87fcc71272081142eb62ed326946d255

build:
  number: 0
  skip: true  # [win and py27]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja  # [win]
  host:
    - python
    - pybind11
    - zlib
  run: 
    - python

test:
  commands:
    - gemmi --help
  imports: 
    - gemmi

about:
  home: https://project-gemmi.github.io/
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE.txt
  summary: 'Macromolecular crystallography library and utilities.'
  doc_url: https://gemmi.readthedocs.io/
  dev_url: https://github.com/project-gemmi/gemmi

extra:
  recipe-maintainers:
    - mcs07
