{% set name = "gemmi" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/project-gemmi/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: a6c3e86fdabeb3f5b662826e3155ed9793a2d90043b66d5f0448e34437accd15

build:
  number: 0
  skip: true  # [win and py27]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja  # [win]
  host:
    - pip
    - python
    - pybind11
    - zlib
  run:
    - python

test:
  commands:
    - gemmi --help
    - python -m gemmi-examples
  imports:
    - gemmi

about:
  home: https://project-gemmi.github.io/
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE.txt
  summary: Macromolecular crystallography library and utilities.
  doc_url: https://gemmi.readthedocs.io/
  dev_url: https://github.com/project-gemmi/gemmi

extra:
  recipe-maintainers:
    - mcs07
