travis:
  secure:
    BINSTAR_TOKEN: R9u78FUq7ndGUyYA+afTr/xkKvhoCh7SbUtH6SRJtv3Svq/1swoOwZk07Sa1g3clizbuBnHA2ulNrZf2qfoyprA9rRlOAv//Hb3LwXEQmOR0Yk+buUdGM20dwfUjo0xo2VJhFvWDoquPcrgFv1JnmGs48x4a1An+OExlvJRMHp3ksluxo+riECJukkkc5ascG+nyEOmsXnkYhADCaH98wJgnCInGr1RAJmhEa+AgaIi6WaN0Ed2ECgXC1tRWh1AUdbzg67lRkNipj5Vm7QZP4DZrIOM722TqCWYX26noXrXdj3VmH+U5yjka4+Ot0xtEprbPptT2NUY8rFX4cELB3an7lbDNmPXL6CMUHbqZiG7cH2Wk3VkJGgVVjvVQKxK7X2fy7PyVFTbGHD5cLztItF/c3o+lpAbMCr9OaRiAbYEXsS0IPkiXSFY18Bg8UGOIcSzkY+sHHNNoxJU8FJEVAALuFm2xDjCXqddIAKJrwmh25EzoxJOUD8hEHSMlmpdbb9yRi7Ktjpb+88uGqmqNeLbVd1qMZhJqG2r8YrUHE+bAfGmvmcdGv6Y5eYjzwZeQFrLtmXQtzHOz9WJb/dusdxuvMYct6Kv9roznUNySAG+eQoDbwm/iHcf/vs2gCLbaefIgi2irue6sQ69n3Fjv7kMODDGyy9NAH18E9xfNFvs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
